/**
 * Loads and normalizes the NYC subway station catalog from the bundled JSON
 * generated by `scripts/build-stations.ts`.
 *
 * Direction-specific stop IDs are produced by appending "N" / "S" to the
 * parent GTFS stop id. This is the convention NYCT uses for every subway
 * division (it does NOT apply to Staten Island Railway, which uses raw stop
 * ids without suffixes; the SI feed is handled separately).
 */
import rawStations from "./data/stations.json";
import type { Station } from "./types";

interface RawStationRow {
  gtfsStopId: string;
  stationId: string;
  complexId: string;
  division: string;
  line: string;
  name: string;
  borough: string;
  cbd: boolean;
  routes: string[];
  structure: string;
  lat: number;
  lng: number;
  northLabel: string;
  southLabel: string;
  ada: number;
}

let cache: Station[] | null = null;
let byParentStopId: Map<string, Station> | null = null;
let byDirectionalStopId: Map<string, { station: Station; direction: "N" | "S" }> | null = null;

function buildIndex(): Station[] {
  const rows = rawStations as RawStationRow[];
  const stations: Station[] = rows.map((r) => {
    const isSir = r.division === "SIR";
    const stopIds = {
      // SIR uses raw stop ids; everything else uses N/S suffixes in the
      // realtime feed. We store both so callers can match without caring.
      N: isSir ? r.gtfsStopId : `${r.gtfsStopId}N`,
      S: isSir ? r.gtfsStopId : `${r.gtfsStopId}S`,
    };
    return {
      gtfsStopId: r.gtfsStopId,
      stationId: r.stationId,
      complexId: r.complexId,
      name: r.name,
      borough: r.borough,
      division: r.division,
      line: r.line,
      routes: r.routes,
      structure: r.structure,
      lat: r.lat,
      lng: r.lng,
      directionLabels: { N: r.northLabel, S: r.southLabel },
      ada: r.ada,
      stopIds,
    };
  });

  // Build lookup indexes
  byParentStopId = new Map(stations.map((s) => [s.gtfsStopId, s]));
  byDirectionalStopId = new Map();
  for (const s of stations) {
    byDirectionalStopId.set(s.stopIds.N, { station: s, direction: "N" });
    byDirectionalStopId.set(s.stopIds.S, { station: s, direction: "S" });
  }

  // Stable sort: by name, then borough (helps the search UI).
  stations.sort((a, b) => {
    const n = a.name.localeCompare(b.name);
    if (n !== 0) return n;
    return a.borough.localeCompare(b.borough);
  });
  return stations;
}

export function getAllStations(): Station[] {
  if (!cache) cache = buildIndex();
  return cache;
}

export function getStationByStopId(parentStopId: string): Station | undefined {
  if (!cache) cache = buildIndex();
  return byParentStopId!.get(parentStopId);
}

export function resolveDirectionalStopId(
  stopId: string,
): { station: Station; direction: "N" | "S" } | undefined {
  if (!cache) cache = buildIndex();
  return byDirectionalStopId!.get(stopId);
}

/**
 * Routes that serve a station, expanded with realistic variants (e.g. <6>
 * express is reported as "6X" in GTFS-RT but appears as "6" in static data).
 */
export function expectedRoutesForStation(station: Station): Set<string> {
  const set = new Set<string>(station.routes);
  for (const r of station.routes) {
    // Add express variants used in NYCT GTFS-RT trip_id encoding
    if (r === "6") set.add("6X");
    if (r === "7") set.add("7X");
    if (r === "F") set.add("FX");
  }
  return set;
}

/** Default station: Grand Av-Newtown, Queens (M/R). */
export const DEFAULT_STATION_ID = "G12";
